### ISSUE TITLE
Multiple reports of whitescreen on iPad when scanner programmatically closed

### ISSUE THREAD

**Issue by kylex** [Scandit/barcodescanner-sdk-cordova#63] opened 2017-02-07 20:08 UTC
Since upgrading to the latest version of the plugin, we've been getting multiple reports of a white screen when the scanner closes after scanning on the iPad (and only on the iPad).

We've been unable to reproduce ourselves, but have had enough separate reports to believe the issue exists.

**Comment by biasmv** [comment] 2017-02-07 20:32
Thanks for the report. We will try to reproduce the issue on our side. Any additional information you have will help us to narrow down the issue more quickly. For example:

- Do you know if this only happens on certain iPad models?
- Do you know if this only happens on certain iOS versions? 
- Could you provide additional information on how you are starting and stopping the scanner, so we can use the same setup on our side?

**Comment by kylex** [comment] 2017-02-07 21:59
iOS 10.2.1
Reported iPad models showing issue:
iPad Air 2, iPad Pro


```
Scandit.License.setAppKey("APP_KEY_NUMBER");
var settings = new Scandit.ScanSettings();

settings.setSymbologyEnabled(Scandit.Barcode.Symbology.EAN13, true);
settings.setSymbologyEnabled(Scandit.Barcode.Symbology.UPC12, true);
settings.setSymbologyEnabled(Scandit.Barcode.Symbology.EAN8, true);

var picker = new Scandit.BarcodePicker(settings);
picker.getOverlayView().showSearchBar(true);
picker.getOverlayView().setTorchEnabled(false);
picker.show(success, success, failure);
picker.startScanning();

function success(session) {
  if (jQuery.type(session) === "object") {
        ean = session.newlyRecognizedCodes[0].data;
        var code_type = session.newlyRecognizedCodes[0].symbology;
    }
    else {
      ean = session;
    }
    // Do stuff with ean
}

function failure() {
  // empty function
}
```

As I receive more information I will update this ticket.

**Comment by biasmv** [comment] 2017-02-08 11:09
We have tried to reproduce on the iPad Pro running iOS 10.2.1 using the code you have provided. We were not able to reproduce the issue so far, even with hundreds of camera restarts. It's possible that the conditions in our test were not close enough to the conditions that trigger the issue, or that the issue is just very rare. We will run some additional tests on our side and keep you posted if there is progress.

**Comment by kylex** [comment] 2017-02-09 07:44
Don't know if this will help at all, but asked a user to send a video of issue:
https://youtu.be/q2TvGqSTyaI

**Comment by kylex** [comment] 2017-02-09 17:47
@biasmv we've discovered what the underlying issue is, and it has nothing to do with Scandit. I appreciate your willingness to look into this for us. Feel free to close this issue.

**Comment by biasmv** [comment] 2017-02-09 19:53
Thanks for letting us know. Glad you were able to resolve the issue!

**Comment by kylex** [comment] 2017-02-11 06:41
Okay, I've discovered the underlying issue, but am unable to resolve:
When iPad is in landscape mode, and both the **cordova scandit** plugin AND the **cordova-plugin-statusbar** plugin are installed, then a white screen presents after a scan (or cancelling a scan).

Cordova is pointing it's finger at Scandit, so I thought I'd reopen this issue again.

**Comment by biasmv** [comment] 2017-02-11 08:52
@kylex: part of the conversation seems to be missing. I've received nofitications by e-mail, but am unable to see the messages here. Is the information from these messages still valid? If so, it would be great if you could send us a sample to reproduce the issue?

**Comment by kylex** [comment] 2017-02-11 18:37
Yes, sorry, it is still valid.

Having the statusbar plugin installed along with the scandit plugin causes this issue for BOTH the iPhone and iPad in landscape mode only.

**Comment by kylex** [comment] 2017-02-11 19:18
Okay, I've confirmed that the issue exists by doing this:

1. Create a basic helloworld cordova app as described in their docs
`cordova create hello com.example.hello HelloWorld`
2. Install the ios platform: 
`cordova platform add ios`
3. Install only the two plugins:
```
cordova plugin add cordova-plugin-statusbar
cordova plugin add /path/to/scanditplugin
```
4. Setup a scan button on the cordova index page and trigger using javascript as shown above.
(I'm using jQuery, but obviously not necessary)
5. `cordova build ios`
6. Run on iPad or iPhone in landscape mode. 
7. Bring up scanner and scan an item.
8. White screen.

**Comment by biasmv** [comment] 2017-02-13 16:02
Thanks! With the new instructions I was able to reproduce the issue on our side. From what I can tell, this appears to be an issue with the cordova status bar plugin code.  I've got a partial fix, but I'm not sure I'm understanding all of the code around the area where the problem happens. Did you already report the issue to cordova-plugin-statusbar? Could you point me to the ticket if you did? Otherwise, I'll open a new ticket together with a suggested patch to fix the issue.

**Comment by kylex** [comment] 2017-02-14 21:19
I have _not_ opened an issue to cordova-plugin-statusbar; please do.

**Comment by biasmv** [comment] 2017-02-15 11:04
It appears that the issue has been fixed in the master branch of cordova-plugin-statusbar. It's not yet part of any release. You can either update your app to use cordova-plugin-statusbar master branch, or will have to wait until the fix makes it into the next release.

**Comment by kylex** [comment] 2017-02-15 20:19
Sounds good, thank you.

**Closed** 2017-05-15 12:25 UTC
